cvm-version: 0.14.8
cpus: 120
memory: 1048576
gpus: 8

networks:
  dev:
    egress: open

volumes:
  - name: workspace
    exec: true

containers:
  - name: "workspace"
    image: "ghcr.io/tinfoilsh/confidential-ubuntu@sha256:3c96130f0c586e5f4b301111624f7dbd4dbb942894611679518fb165496ed917" # v0.6.5
    runtime: nvidia
    gpus: all
    restart: on-failure
    cvm_admin: true
    stop_signal: SIGRTMIN+3
    stop_timeout: 120
    networks: [dev]
    volumes: [workspace:/mnt/disk]

    ports: ["22:22"]

    env:
      - SSH_KEYS: |-
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKcW8gy3qDjGP3iBIggbIeiUl47+tm3zwWcCi0ww/QZG
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHqerhhrFex4XpSs4atO8I/I6G2TfhmWZOeK7SPuGhuP

    tmpfs:
      /run: "rw,nosuid,nodev,mode=755"

    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 30s

shim:
  upstream-port: 22
  authenticated: false
